name: Build and Deploy GH Runner on ACI

on:
  push:
    branches: [main]
    paths: 
      - Dockerfile
  workflow_dispatch:

env:
  IMAGE_NAME: aci-runner
  IMAGE_TAG: ${{ github.run_number }}
  RUNNER_REPOSITORY_URL: https://github.com/mattmajestic/aci-runner # Replace 'yourUsername' with your actual GitHub username
  RESOURCE_GROUP: azure-vm
  LOCATION: eastus
  ACR_NAME: majesticcoding.azurecr.io # Replace with your ACR name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate GitHub Runner Registration Token
        id: generate-token
        run: |
          TOKEN=$(curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/mattmajestic/aci-runner/actions/runners/registration-token" | jq -r .token)
          echo "::set-output name=token::$TOKEN"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Build and Push to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ env.ACR_NAME }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker build . -f Dockerfile -t ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances
        uses: Azure/aci-deploy@v1
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          location: ${{ env.LOCATION }}
          cpu: 2
          dns-name-label: mattmajestic${{ github.run_number }}
          image: ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          name: aci-runner-${{ github.run_number }}
          registry-login-server: ${{ env.ACR_NAME }}
          registry-username: majesticcoding
          registry-password: ${{ secrets.ACR_PASSWORD }}
          environment-variables: RUNNER_REPOSITORY_URL=${{ env.RUNNER_REPOSITORY_URL }} RUNNER_TOKEN=${{ steps.generate-token.outputs.token }}
